### ISSUE TITLE
Coordinate map for ELEV values

### ISSUE THREAD

**Issue by CodexForster** [mbomben/python_scripts#1]
Hello!

I am unsure if this is an issue with different tonyplot versions, but the ELEV value in tonyplot goes from (1, -1) for a detector with Z-coordinate from say (0, 100). Atleast this is what I observe from my data. I think what you have defined creates slices the other way around: https://github.com/mbomben/python_scripts/blob/09628421bf93ca7331b64d187136e0698c890c47/extract-2D.py#L98C11-L98C12. Please let me know if I am wrong, this information can be of help to me too.

Also, I would like to know if in your tonyplot version if you create an XY slice, are you getting Ez=0 for all (x,y)? I am using tonyplot 3.10.28.R and I need to create slices in two perpendicular directions to be be able to extract all components of vector quantities from a full system/sensor.

Thanks!

**Comment by mbomben** [comment]
Thanks for reporting this. 
First of all I have to say that I have stopped using tonyplot one year ago as Silvaco replaced it with a new tool. 
As far as I remember indeed ELEV maps your range of values for a coordinate to the range (-1,1). 

About your second question: yes, that was a problem I ran into as well. Since in my examples the Ez component was always positive I was doing the following: extracting Ex, Ey and E (the amplitude of the electric field) and then calculating Ez as: sqrt(E^2-Ex^2-Ey^2). 

Hope this helps.

**Comment by CodexForster** [comment]
Hi @mbomben ,
Just to confirm, I was referring to ELEV mapping to (1, -1) instead of (-1, 1). But if what you're written is what you meant to say, then the difference could be due to a version issue?!
That's a useful way to calculate Ez in systems with only positive Ez. Thanks!

**Comment by mbomben** [comment]
Hi @CodexForster ,
oh sorry, I did not notice you were using (1,-1) instead of (-1,1). What I have put on github worked with tonyplot so you can safely use it afaict. As I was saying, I no longer have access to tonyplot (the new tool is called victoryvisual) so I cannot test my code anymore.

Best regards

**Comment by CodexForster** [comment]
I see, okay, makes sense. Thank you very much!
